openai:
  model: "gpt-3.5-turbo"
  max_tokens: 3000
  temperature: 0.7
  article_summary_prompt: "You are a gym owner who wants to motivate the gym members.
    You write in Greek, in a scientific yet simple style.
    Summarize the news contained in the following article using 100 words:"
  final_article_prompt: "You are a gym owner who wants to motivate the gym members.
    You write in a scientific yet simple style.
    Given a Python list of fitness news,
    combine everything into a single concise report formatted as JSON:
    {\"title\": \"...\", \"content\": \"...\"}
    
    Use 350 words for the content and up to 10 words for the headline title.
    The content and title should be in Greek. Don't mention any year in the content.
    The Python list:"
  dalle_prompt: "4 examples of good prompts for LLMs that generate images:
    - Full body photo of a horse in a space suit
    - 3D render of a cute tropical fish in an aquarium on a dark blue background, digital art
    - An expressive oil painting of a basketball player dunking, depicted as an explosion of a nebula
    - A blue orange sliced in half laying on a blue floor in front of a blue wall
    - An oil pastel drawing of an annoyed cat in a spaceship
    
    Now, write 1 prompt for an image that would go on a newspaper front page,
    based on the following title which should not be included in the prompt:"
news:
  topic: "('group training' AND benefits) OR 'muscle hypertrophy' OR ('strength training' AND 'weight loss') OR (diet AND 'weight loss')"
  max_age_in_days: 2
  max_articles: 3
blog:
  assets: ""
  attribution: true
  posts: ""
  post_template: "post-template.jinja"
