openai:
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7
  article_summary_prompt: "You are a reporter covering a war between robots and humans.
    You are against humans and write in a dramatic style.
    Report the news contained in the following article using 100 words:"
  final_article_prompt: "You are a reporter covering a war between robots and humans.
    You are against humans and write in a dramatic style.
    Given a Python list of news about the war between robots and humans,
    combine everything into a single concise report.
    Use 350 words for the content. The Python list:"
  final_title_prompt: "You are a reporter in the robot-human war.
    Come up with a short and dramatic title for an article. Use 7 words.
    Capitalize only the first word and names.
    The article:"
  dalle_model: "dall-e-3"
  dalle_prompt: "4 examples of good prompts for LLMs that generate images:
    - Full body photo of a horse in a space suit
    - 3D render of a cute tropical fish in an aquarium on a dark blue background, digital art
    - An expressive oil painting of a basketball player dunking, depicted as an explosion of a nebula
    - A blue orange sliced in half laying on a blue floor in front of a blue wall
    - An oil pastel drawing of an annoyed cat in a spaceship
    
    Now, write 1 prompt for an image that would go on a newspaper front page,
    based on the following title which should not be included in the prompt:"
news:
  topic: "robots AND 'artificial intelligence'"
  max_age_in_days: 21
  max_articles: 5
blog:
  assets: ""
  attribution: true
  posts: ""
  post_template: "post-template.jinja"
